---
- name: Pull Docker Image of Calculator
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: Pull image
    docker_image:
      name: anwit/calculator2023:latest
      source: pull
  - name: Start docker service
    service:
      name: docker
      state: started
  - name: Running container
    shell: docker run -it -d --name Calculator20231027 anwit/calculator2023